# Generated by Django 4.2.11 on 2024-10-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankowanie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='number',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
