# Generated by Django 5.2.4 on 2025-07-31 19:50

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('\\d{11}')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(validators=[django.core.validators.RegexValidator('\\d{9}')]),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
