# Generated by Django 5.2.4 on 2025-08-05 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_client_date_birth_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+")]),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+")]),
        ),
    ]
