# Generated by Django 5.2.4 on 2025-09-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_card_pin_alter_card_account_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('SAVING', 'Saving'), ('CREDIT', 'Credit')], default='REGULAR'),
        ),
    ]
