# Generated by Django 5.2.4 on 2025-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
