# Generated by Django 5.2.4 on 2025-09-28 18:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='pin',
            field=models.CharField(default='0000', validators=[django.core.validators.RegexValidator('\\d{4}')]),
        ),
    ]
