# Generated by Django 5.2.4 on 2026-01-25 23:47

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_card_number_alter_card_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(error_messages={}, max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(unique=True, validators=[django.core.validators.RegexValidator('\\d{11}')], verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(validators=[django.core.validators.RegexValidator('\\d{9}')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
