# Generated by Django 5.2.4 on 2026-01-26 10:27

import banking.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_client_date_birth_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_birth',
            field=models.DateField(error_messages={'required': 'Date of birth is required', 'required_age': 'Required age above 18'}, validators=[banking.validators.validate_date_birth_above_18_today], verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(error_messages={'max_length': 'First name must be shorter than 150 characters', 'required': 'First name is required'}, max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(error_messages={'max_length': 'Last name must be shorter than 150 characters', 'required': 'Last name is required'}, max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(error_messages={'consist': 'PESEL must consist of 11 digits', 'incorrect': 'Incorrect PESEL', 'required': 'PESEL is required'}, unique=True, validators=[banking.validators.validate_pesel], verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'required': 'Phone number is required'}, validators=[django.core.validators.RegexValidator('\\d{9}')], verbose_name='phone number'),
        ),
    ]
