# Generated by Django 5.2.4 on 2026-02-08 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_alter_client_date_birth_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(error_messages={'invalid': 'First name is invalid, use letters, spaces, apostrophes, hyphen', 'max_length': 'First name must be shorter than 150 characters', 'required': 'First name is required'}, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+$")], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(error_messages={'invalid': 'Last name is invalid, use letters, spaces, apostrophes, hyphen', 'max_length': 'Last name must be shorter than 150 characters', 'required': 'Last name is required'}, max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+$")], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
