# Generated by Django 5.2.4 on 2026-03-11 17:10

import banking.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_alter_client_first_name_alter_client_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('SAVING', 'Saving'), ('CREDIT', 'Credit')], default='REGULAR'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+$")], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator("^[A-Za-zĄąĆćĘęŁłŃńÓóŚśŹźŻż' -]+$")], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pesel',
            field=models.CharField(error_messages={'consist': 'PESEL must consist of 11 digits', 'invalid': 'Incorrect PESEL', 'required': 'PESEL is required'}, unique=True, validators=[banking.validators.validate_pesel], verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'Phone number is incorrect, can contains only 9 digits', 'required': 'Phone number is required'}, validators=[django.core.validators.RegexValidator('\\d{9}')], verbose_name='phone number'),
        ),
    ]
