# Generated by Django 5.2.4 on 2026-03-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_alter_account_type_account_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type_account',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('SAVING', 'Saving'), ('CREDIT', 'Credit')], default='PERSONAL'),
        ),
    ]
