# Generated by Django 5.2.4 on 2026-07-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_alter_account_type_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
