# Generated by Django 5.2.4 on 2026-08-23 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0014_alter_account_money_alter_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(error_messages={'invalid': 'Phone number is incorrect, can contains only 9 digits', 'required': 'Phone number is required'}, validators=[django.core.validators.RegexValidator('^\\d{9}$')], verbose_name='phone number'),
        ),
    ]
