# Generated by Django 5.2.4 on 2026-07-04 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0013_alter_account_number_alter_card_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('internal_transfer_type', models.BooleanField(default=False)),
                ('external_recipient_number', models.IntegerField(null=True)),
                ('external_recipient_name', models.CharField(blank=True, max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
                ('internal_transfer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_account', to='banking.account')),
            ],
        ),
    ]
