# Generated by Django 5.2.4 on 2026-07-10 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='external_recipient_name',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='external_recipient_number',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='internal_transfer_account',
        ),
        migrations.AddField(
            model_name='transfer',
            name='connected_account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='connected account name'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='connected_account_number',
            field=models.CharField(default=111111, max_length=6, validators=[django.core.validators.RegexValidator('\\d{6}')], verbose_name='connected account number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='internal_transfer_type',
            field=models.BooleanField(default=False, verbose_name='internal transfer type'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='money',
            field=models.IntegerField(verbose_name='money'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
