# Generated by Django 5.2.4 on 2026-08-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0015_alter_client_phone_number'),
        ('transfers', '0002_alter_transfer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='banking.account'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='money'),
        ),
    ]
